data:
  dataset: {name: LandUse, samples: 25253, type: private}
  datasetLoadOption: batch
  kfold: 1
  mapping:
    Image:
      options: {Augmentation: false, Height: 28, Normalization: false, Resize: false,
        Scaling: 1, Width: 28, height_shift_range: 0, horizontal_flip: false, pretrained: None,
        rotation_range: 0, shear_range: 0, vertical_flip: false, width_shift_range: 0}
      port: InputPort0
      shape: ''
      type: Image
    Rating:
      options: {Normalization: false, Scaling: 1}
      port: OutputPort0
      shape: ''
      type: Categorical
  numPorts: 1
  samples: {split: 3, test: 3787, training: 17677, validation: 3787}
  shuffle: true
model:
  connections:
  - {source: Convolution2D_5, target: Convolution2D_6}
  - {source: Convolution2D_6, target: MaxPooling2D_3}
  - {source: Convolution2D_1, target: Convolution2D_2}
  - {source: Convolution2D_2, target: MaxPooling2D_1}
  - {source: MaxPooling2D_2, target: Convolution2D_5}
  - {source: Convolution2D_3, target: Convolution2D_4}
  - {source: Dense_2, target: Output_1}
  - {source: Dropout_1, target: Dense_2}
  - {source: Convolution2D_4, target: MaxPooling2D_2}
  - {source: Input_1, target: Convolution2D_1}
  - {source: Dense_1, target: Dropout_1}
  - {source: Flatten_1, target: Dense_1}
  - {source: MaxPooling2D_3, target: Flatten_1}
  - {source: MaxPooling2D_1, target: Convolution2D_3}
  layers:
  - args: {}
    class: Input
    name: Input_1
    x: 64
    y: 45
  - args: {activation: relu, nb_col: '2', nb_filter: '3', nb_row: '2'}
    class: Convolution2D
    name: Convolution2D_1
    x: 64
    y: 169
  - args: {activation: relu, nb_col: '2', nb_filter: '3', nb_row: '2'}
    class: Convolution2D
    name: Convolution2D_2
    x: 61
    y: 273
  - args: {}
    class: MaxPooling2D
    name: MaxPooling2D_1
    x: 70
    y: 369
  - args: {activation: relu, nb_col: '2', nb_filter: '3', nb_row: '2'}
    class: Convolution2D
    name: Convolution2D_3
    x: 68
    y: 464
  - args: {nb_col: '2', nb_filter: '3', nb_row: '2'}
    class: Convolution2D
    name: Convolution2D_4
    x: 75
    y: 566
  - args: {}
    class: MaxPooling2D
    name: MaxPooling2D_2
    x: 69
    y: 665
  - args: {activation: relu, nb_col: '2', nb_filter: '3', nb_row: '2'}
    class: Convolution2D
    name: Convolution2D_5
    x: 395
    y: 47
  - args: {activation: relu, nb_col: '2', nb_filter: '3', nb_row: '2'}
    class: Convolution2D
    name: Convolution2D_6
    x: 392
    y: 165
  - args: {}
    class: MaxPooling2D
    name: MaxPooling2D_3
    x: 394
    y: 266
  - args: {}
    class: Flatten
    name: Flatten_1
    x: 403
    y: 366
  - args: {activation: relu, output_dim: '2028'}
    class: Dense
    name: Dense_1
    x: 396
    y: 455
  - args: {p: '0.7'}
    class: Dropout
    name: Dropout_1
    x: 395
    y: 553
  - args: {activation: sigmoid, output_dim: '11'}
    class: Dense
    name: Dense_2
    x: 403
    y: 682
  - args: {}
    class: Output
    name: Output_1
    x: 405
    y: 820
params:
  advance_params: true
  batch_size: 32
  is_custom_loss: false
  loss_func: binary_crossentropy
  num_epoch: 10
  optimizer: {name: Adam}
project: Land Use Classification
